### ISSUE TITLE
Déploiement de 4 conteneurs (front, backend, AI, mysql) avec Docker Compose ou Kubernetes

### ISSUE THREAD

**Issue by serignemodouthiam** [SSDM2/ESP_DBEval#7]
**Description :**

Cette tâche consiste à ajouter un conteneur pour la base de données (par exemple, MySQL, PostgreSQL, MongoDB, etc.) en local et à l'intégrer avec les conteneurs existants (front-end, back-end, AI). L'objectif est de déployer une base de données dans un environnement local, garantir son accessibilité depuis les autres services et veiller à la persistance des données. L'utilisation de Docker Compose ou Kubernetes est recommandée pour l'orchestration des services.

**Sous-tâches à accomplir** :

- [ ] 1. **Choisir le type de base de données** :

   - Sélectionner une base de données compatible (MySQL, PostgreSQL, MongoDB, etc.).

- [ ] 2. **Créer le conteneur de la base de données** :
   - Ajouter un service pour la base de données dans le fichier `docker-compose.yml` ou le fichier de configuration Kubernetes.

- [ ] 3. **Configurer la persistance des données** :
   - Assurer la persistance des données de la base de données avec Docker Volumes ou Kubernetes Persistent Volumes.

- [ ] 4. **Configurer la connexion entre le back-end et la base de données** :
   - Mettre à jour les variables d'environnement dans le back-end pour y inclure les informations de connexion à la base de données.

5. **Vérifier l'intégration** :
   - Tester la connectivité entre la base de données et le back-end, et assurer que l'accès fonctionne comme prévu.

**Critères d'acceptation** :
- Le conteneur de la base de données est opérationnel en local.
- La base de données est correctement intégrée avec le back-end.
- Les données sont persistées entre les redémarrages des services.

---

### Exemple de configuration Docker Compose pour une base de données :

**docker-compose.yml** :
```yaml
version: '3.8'

services:
  frontend:
    image: frontend_image
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    image: backend_image
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
    ports:
      - "5000:5000"
    networks:
      - app-network

  ai:
    image: ai_image
    ports:
      - "6000:6000"
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
```

### Test et Validation :
- Lancez tous les services avec `docker-compose up`.
- Vérifiez que la base de données est accessible depuis le back-end et que les données sont persistées.

---
